//! The peer key: one ed25519 key per local computer, used to sign in to a host
//! when the operator's own SSH config or agent is refused (ADR-0067 §4). It has
//! no passphrase, so it must stay owner-only; it is generated once and reused
//! for every host added from this computer.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

/// The peer key on disk and its public line (`ssh-ed25519 <body> <comment>`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PeerKey {
    pub path: PathBuf,
    pub public_line: String,
}

/// Where the peer key lives inside the Ralphy store.
pub fn key_path_in(store: &Path) -> PathBuf {
    store.join("ssh").join("peer_ed25519")
}

/// The peer key, generated by `generate` only when it does not exist yet. The
/// owner-only restriction is applied on every call, so a key whose mode was
/// widened by hand is narrowed again before it is used.
pub fn ensure_peer_key(
    store: &Path,
    generate: impl FnOnce(&Path) -> Result<()>,
) -> Result<PeerKey> {
    let path = key_path_in(store);
    let dir = store.join("ssh");
    std::fs::create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;
    if !path.is_file() {
        generate(&path).context("generating the peer key")?;
    }
    crate::owner_only::set_owner_only(&path)?;
    let public = PathBuf::from(format!("{}.pub", path.display()));
    let public_line = std::fs::read_to_string(&public)
        .with_context(|| format!("reading the peer key's public half {}", public.display()))?
        .trim()
        .to_string();
    Ok(PeerKey { path, public_line })
}

/// The base64 body of a public key line: its second whitespace field.
pub fn key_body(public_line: &str) -> Option<&str> {
    public_line.split_whitespace().nth(1)
}

#[cfg(test)]
mod tests {
    use super::*;

    const PUBLIC: &str = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPeer ralphy-peer@anvil\n";

    fn fake_keygen(path: &Path) -> Result<()> {
        std::fs::write(path, "PRIVATE")?;
        std::fs::write(format!("{}.pub", path.display()), PUBLIC)?;
        Ok(())
    }

    #[test]
    fn peer_key_is_owner_only_and_generated_once() {
        let store = tempfile::tempdir().expect("a temp store");
        let first = ensure_peer_key(store.path(), fake_keygen).expect("a first key");
        assert_eq!(first.path, key_path_in(store.path()));
        assert_eq!(first.public_line, PUBLIC.trim());

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&first.path)
                .expect("the key metadata")
                .permissions()
                .mode();
            assert_eq!(mode & 0o777, 0o600);
        }
        #[cfg(windows)]
        {
            use crate::owner_only::tests::{read_dacl, Dacl};
            assert_eq!(
                read_dacl(&first.path),
                Dacl {
                    protected: true,
                    ace_count: 1,
                    first_is_user_full_access: true,
                }
            );
        }

        let second =
            ensure_peer_key(store.path(), |_| panic!("generated twice")).expect("the same key");
        assert_eq!(second, first);
    }

    #[test]
    fn peer_key_body_is_the_second_field() {
        assert_eq!(key_body(PUBLIC), Some("AAAAC3NzaC1lZDI1NTE5AAAAIPeer"));
        assert_eq!(key_body("ssh-ed25519"), None);
    }
}
