//! Ralphy's policy document (ADR-0043 D5).
//!
//! The vendor evaluates policy rules across tiers; a document passed on `--policy`
//! is sovereign over the user tier, so an argv `deny` beats a user rule carrying a
//! far higher priority number. That sovereignty is what makes one rule
//! load-bearing: `invoke_agent` is always denied, and a denied tool is absent from
//! the model's tool schema rather than refused at call time — the run cannot fan
//! out into subagents Ralphy neither budgets nor observes.
//!
//! The operator's own rules are not discarded, but only their RESTRICTIVE ones are
//! imported: a `deny` they wrote is a decision Ralphy honours, while an `allow` or
//! an `ask_user` would either widen the run's blast radius or park it on a prompt
//! no one is there to answer.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

/// The marker a denied delegation carries, so a refusal is recognisable in the
/// stream rather than reading as an ordinary tool error.
pub(crate) const DENY_MARKER: &str = "RALPHY_POLICY_DENIED_SUBAGENT";

/// The file Ralphy writes and passes on `--policy`.
const POLICY_FILE: &str = "ralphy-policy.toml";

/// Ralphy's policy document: its own non-negotiable rule first, then the
/// operator's imported denials verbatim.
///
/// `run_shell_command` is deliberately NOT denied: a Ralphy run commits through
/// git and must shell out. D5's shell deny applies only where a run should not
/// shell out, which is not the run path.
pub(crate) fn ralphy_policy(imported: &[String]) -> String {
    let mut out = String::from(
        "# Generated by Ralphy. Passed on `--policy`, which is sovereign over the\n\
         # user tier (ADR-0043 D5). Edits here are overwritten every run.\n\n\
         [[rule]]\n\
         toolName = \"invoke_agent\"\n\
         decision = \"deny\"\n\
         priority = 100\n",
    );
    out.push_str(&format!("denyMessage = \"{DENY_MARKER}\"\n"));
    for rule in imported {
        out.push('\n');
        out.push_str(rule.trim_end());
        out.push('\n');
    }
    out
}

/// Every `decision = "deny"` rule in the operator's `policies/` directory,
/// re-emitted as TOML rule bodies.
///
/// `allow` and `ask_user` rules are dropped on purpose (see the module doc). A
/// missing directory, an unparsable file or a file with no rules is not an error —
/// most operators have no `policies/` at all, and a broken one must not stop a run
/// that is about to be MORE restrictive than they asked for.
pub(crate) fn import_deny_rules(policies_dir: Option<&Path>) -> Vec<String> {
    let Some(dir) = policies_dir else {
        return Vec::new();
    };
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut files: Vec<PathBuf> = entries
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("toml"))
        .collect();
    files.sort();

    let mut out = Vec::new();
    for file in files {
        let Ok(text) = std::fs::read_to_string(&file) else {
            continue;
        };
        let Ok(doc) = text.parse::<toml::Table>() else {
            tracing::warn!("skipping unparsable gemini policy {}", file.display());
            continue;
        };
        let Some(rules) = doc.get("rule").and_then(|v| v.as_array()) else {
            continue;
        };
        for rule in rules {
            let is_deny = rule
                .get("decision")
                .and_then(|d| d.as_str())
                .is_some_and(|d| d == "deny");
            if !is_deny {
                continue;
            }
            let mut table = toml::Table::new();
            table.insert("rule".into(), toml::Value::Array(vec![rule.clone()]));
            match toml::to_string(&table) {
                Ok(body) => out.push(body),
                Err(e) => tracing::warn!("skipping unserializable gemini deny rule: {e}"),
            }
        }
    }
    out
}

/// Write the document into Ralphy's own root and return the path to pass on argv.
pub(crate) fn write_policy(root: &crate::root::GeminiRoot, body: &str) -> Result<PathBuf> {
    let path = root.cli_dir().join(POLICY_FILE);
    std::fs::write(&path, body).with_context(|| format!("writing {}", path.display()))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The one rule that is never negotiable, present even with nothing imported.
    #[test]
    fn the_policy_always_denies_invoke_agent() {
        let body = ralphy_policy(&[]);
        let doc: toml::Table = body.parse().expect("the generated document must parse");
        let rules = doc["rule"].as_array().expect("a [[rule]] array");
        assert_eq!(rules.len(), 1, "{body}");
        assert_eq!(rules[0]["toolName"].as_str(), Some("invoke_agent"));
        assert_eq!(rules[0]["decision"].as_str(), Some("deny"));
        assert_eq!(rules[0]["denyMessage"].as_str(), Some(DENY_MARKER));
        // A Ralphy run commits through git: the shell is NOT denied.
        assert!(!body.contains("run_shell_command"), "{body}");
    }

    /// D5's import rule: the operator's restrictive intent survives, their
    /// permissive and prompting rules do not.
    #[test]
    fn importing_keeps_deny_and_drops_allow_and_ask_user() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(
            dir.path().join("a-deny.toml"),
            b"[[rule]]\ntoolName = \"write_file\"\ndecision = \"deny\"\npriority = 50\n",
        )
        .unwrap();
        std::fs::write(
            dir.path().join("b-allow.toml"),
            b"[[rule]]\ntoolName = \"run_shell_command\"\ncommandPrefix = \"git push\"\ndecision = \"allow\"\npriority = 900\n",
        )
        .unwrap();
        std::fs::write(
            dir.path().join("c-ask.toml"),
            b"[[rule]]\ntoolName = \"read_file\"\ndecision = \"ask_user\"\npriority = 10\n",
        )
        .unwrap();
        // Not a policy file at all.
        std::fs::write(dir.path().join("notes.md"), b"# ignore me\n").unwrap();

        let imported = import_deny_rules(Some(dir.path()));
        assert_eq!(imported.len(), 1, "{imported:?}");

        let body = ralphy_policy(&imported);
        let doc: toml::Table = body.parse().expect("the generated document must parse");
        let rules = doc["rule"].as_array().unwrap();
        assert_eq!(rules.len(), 2, "{body}");
        assert_eq!(
            rules[0]["toolName"].as_str(),
            Some("invoke_agent"),
            "Ralphy's own rule comes first: {body}"
        );
        assert_eq!(rules[1]["toolName"].as_str(), Some("write_file"));
        assert_eq!(rules[1]["decision"].as_str(), Some("deny"));
        assert_eq!(rules[1]["priority"].as_integer(), Some(50));
        assert!(
            !body.contains("git push"),
            "a permissive rule must never be imported: {body}"
        );
        assert!(!body.contains("ask_user"), "{body}");
    }

    /// Most operators have no `policies/` directory; a broken one must not stop a
    /// run that is about to be more restrictive than they asked for.
    #[test]
    fn importing_tolerates_a_missing_or_broken_directory() {
        assert!(import_deny_rules(None).is_empty());
        let dir = tempfile::tempdir().unwrap();
        assert!(import_deny_rules(Some(&dir.path().join("nope"))).is_empty());
        assert!(import_deny_rules(Some(dir.path())).is_empty());
        std::fs::write(dir.path().join("bad.toml"), b"[[rule\n").unwrap();
        assert!(import_deny_rules(Some(dir.path())).is_empty());
        // A parsable file with no rules at all.
        std::fs::write(dir.path().join("empty.toml"), b"other = 1\n").unwrap();
        assert!(import_deny_rules(Some(dir.path())).is_empty());
    }

    /// The document lands inside Ralphy's own root, never the operator's.
    #[test]
    fn the_policy_is_written_into_the_owned_root() {
        let base = tempfile::tempdir().unwrap();
        let root = crate::root::ensure(base.path()).unwrap();
        let body = ralphy_policy(&[]);
        let path = write_policy(&root, &body).unwrap();
        assert!(path.starts_with(&root.home), "{path:?}");
        assert_eq!(std::fs::read_to_string(&path).unwrap(), body);
    }
}
